### PR TITLE
Add Devtoolset 6 images

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by omron93** [comment]
@hhorak RHEL packages are not in Beta (hel-server-rhscl-beta-7-rpms),  they are already released. That is why RHEL7 tests are failing.

**Comment by hhorak** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
https://github.com/sclorg/devtoolset-container/pull/14 is not included for Devtoolset 6 scripts. So RHEL7 tests are failing due to CI OpenStack limitations.

@hhorak Please update tests. Also installing of packages differs from `4-` version of Dockerfiles. Is this intended? (using `centos-sclo-rh-testing` repository and skipping `rpm -V`)

**Comment by hhorak** [comment]
Thanks for the feedback, now it should hopefully be fixed..

**Comment by hhorak** [comment]
[test]

**Comment by omron93** [comment]
Thanks, LGTM.

Last thing, labels in Fedora dockerfile don't match Container Guidelines. But it seems that fedora container guidelines are changing quite fast so not sure that updating this PR solves this problem in long term :-(

**Pull request merged**
