### PR TITLE
This commit deprecates 7-perftools and 7-toolset images.

### PR DESCRIPTION
**Pull request by phracek**
Most information from README.md file were commented out like
versions, installations, usage and test.
Updated files are:
* Makefile
* README.md
* 7-toolset/README.md
* 7-perftools/README.md

container-common-scripts have been updated

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
lgtm, thanks!

**Comment by morrisonlevi** [comment]
What is the suggested replacement for these images?

I tried using devtoolset-8 images as described on this page: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/.

> $ docker pull centos/devtoolset-8-toolchain-centos7

But it doesn't exist:
> Using default tag: latest
Error response from daemon: pull access denied for centos/devtoolset-8-toolchain-centos7, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Pull request merged**
